export 'home/home_page.dart';
export 'login/login_page.dart';
export 'register/register_page.dart';
export 'welcome/welcome_page.dart';
export 'forgetpass/forgetpass_page.dart';
export 'launcher/launcher_page.dart';
export 'news/news_page.dart';
export 'competition/competition_page.dart';
export 'profiles/profile_page.dart';
